<script src="https://staticcdn.ulife.com.br/src.jq/MasterPage/masterPageScripts.js?v=10.732.0"></script>
<script src="https://staticcdn.ulife.com.br/src.jq/require.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/jquery-1.8.0.min.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/JQueryPlugins/jquery-custom-scrollbar-0.5.5/jquery.custom-scrollbar.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/angularjs/angular.1.5.min.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/tinymce/tinymce.min.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/tinymce/ilangtinymce.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/tinymce/plugins/asciimath/js/ASCIIMathMLwFallback.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/settings.js?v=10.732.0"></script><script type="text/javascript" id="" charset="">(function(a,e,c,d,b){a=a[b]=a[b]||{q:[],onReady:function(f){a.q.push(f)}};b=e.createElement(c);b.async=1;b.src=d;d=e.getElementsByTagName(c)[0];d.parentNode.insertBefore(b,d)})(window,document,"script","https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum.js","DD_RUM");function onReadySettings(a){var e=6E3,c=100,d=0,b=setInterval(function(){d+=c;d>=e&&clearInterval(b);typeof ILangSettings!=="undefined"&&(clearInterval(b),a())},c)}
window.DD_RUM.onReady(function(){fetch("/version.txt").then(function(a){a.status===200&&a.text().then(function(e){window.DD_RUM.init({clientToken:"pub031fa212339cfbc4732a07089ec0419d",applicationId:"64187960-8bef-4ff8-968b-3082dc391acc",site:"datadoghq.com",service:"ulife",env:"production",version:e,trackSessionAcrossSubdomains:!0,allowedTracingUrls:[{match:/^https:\/\/((api)?(admin|api|student|social|assessment))\.ulife\.com\.br/,propagatorTypes:["tracecontext"]},{match:/^https:\/\/ulife\.com\.br\/.*\.ashx$/,
propagatorTypes:["tracecontext"]}],traceSampleRate:100,sessionSampleRate:.5,sessionReplaySampleRate:20,trackUserInteractions:!0,trackResources:!0,trackLongTasks:!0,storeContextsAcrossPages:!0,defaultPrivacyLevel:"allow"});onReadySettings(function(){var c={id:ILangSettings.UserID,name:ILangSettings.UserName,admin:ILangSettings.IsUserAdmin,student:ILangSettings.IsUserStudent,organizationId:ILangSettings.OrganizationID};window.DD_RUM.setUser(c)})})})});</script><script id="" text="" charset="" type="text/javascript" src="//app.helphero.co/embed/e7LL8qS3exB"></script>
<script type="text/javascript" id="" charset="">(function(){var l=function(e,g,f,h){this.get=function(a){a+="\x3d";for(var b=document.cookie.split(";"),c=0,k=b.length;c<k;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return null};this.set=function(a,b){var c=new Date;c.setTime(c.getTime()+6048E5);c="; expires\x3d"+c.toGMTString();document.cookie=a+"\x3d"+b+c+"; path\x3d/; "};this.check=function(){var a=this.get(f);if(a)a=a.split(":");else if(100!=e)"v"==g&&(e=Math.random()>=
e/100?0:100),a=[g,e,0],this.set(f,a.join(":"));else return!0;var b=a[1];if(100==b)return!0;switch(a[0]){case "v":return!1;case "r":return b=a[2]%Math.floor(100/b),a[2]++,this.set(f,a.join(":")),!b}return!0};this.go=function(){if(this.check()){var a=document.createElement("script");a.type="text/javascript";a.async=1;a.src=h;document.body&&document.body.appendChild(a)}};this.start=function(){var a=this;"complete"!==document.readyState?window.addEventListener?window.addEventListener("load",function(){a.go()},
!1):window.attachEvent&&window.attachEvent("onload",function(){a.go()}):a.go()}};try{(new l(100,"r","QSI_S_ZN_cNLt9ENyAHQ2FEy","https://zncnlt9enyahq2fey-laureatebr.siteintercept.qualtrics.com/SIE/?Q_ZID\x3dZN_cNLt9ENyAHQ2FEy")).start()}catch(e){}})();</script><div id="ZN_cNLt9ENyAHQ2FEy"></div>
<script type="text/javascript" id="" charset="">(function(a,e,b,f,g,c,d){a[b]=a[b]||function(){(a[b].q=a[b].q||[]).push(arguments)};c=e.createElement(f);c.async=1;c.src="https://www.clarity.ms/tag/"+g;d=e.getElementsByTagName(f)[0];d.parentNode.insertBefore(c,d)})(window,document,"clarity","script","krdrkr9jeq");window.clarity("identify","VMpvr77UfKG7TF2Mv8uwUGaIBstxT7xCAl2\/aErxNi4\x3d");window.clarity("set","RA","52694103898");window.clarity("set","Origem","SIAF");window.clarity("set","Nivel Curso","Graduação");
window.clarity("set","Modalidade","Presencial");window.clarity("set","Marca","UAM");window.clarity("set","Campus","UAM - Avenida Paulista - 734");window.clarity("set","Curso","Ciência da Computação");window.clarity("set","Classifica\u00e7\u00e3o","Veterano");window.clarity("set","Data de Registro","2\/6\/2024 10:21:26 AM");window.clarity("set","Periodo","1");window.clarity("set","Papel","Scholarship, StudentExternalLinks, Certificate, Student, Documentação Acadêmica, Declaração de Regularidade Acadêmica, Missão Calouros, Percentual de Hibridez, Plano de Ensino, StudentValorizza");window.clarity("set","App","false");</script>
<script type="text/javascript" id="" charset="">(function(a,c,e,f,d,b){a.hj=a.hj||function(){(a.hj.q=a.hj.q||[]).push(arguments)};a._hjSettings={hjid:1708103,hjsv:6};d=c.getElementsByTagName("head")[0];b=c.createElement("script");b.async=1;b.src=e+a._hjSettings.hjid+f+a._hjSettings.hjsv;d.appendChild(b)})(window,document,"https://static.hotjar.com/c/hotjar-",".js?sv\x3d");var userId=google_tag_manager["rm"]["13564561"](46)||null;
window.hj("identify",userId,{Holding:"Anima Digital",Marca:"UAM",Campus:"Anima Digital \/ UAM - Avenida Paulista - 734","Organiza\u00e7\u00e3o":"UAM - Avenida Paulista - 734",Curso:"Ciência da Computação",Papel:"Scholarship, StudentExternalLinks, Certificate, Student, Documentação Acadêmica, Declaração de Regularidade Acadêmica, Missão Calouros, Percentual de Hibridez, Plano de Ensino, StudentValorizza",RA:"52694103898",PeriodoAcademico:"1",DataRegistro:"2\/6\/2024 10:21:26 AM",NivelCurso:"Graduação","Classifica\u00e7\u00e3o":"Veterano",Origem:"SIAF",ModalidadeCurso:"Presencial",IsFlutterApp:"false"});</script><script src="https://staticcdn.ulife.com.br/src.jq/common.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/ilang-util.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/ilang-signalr-connectExtensions.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/baseangular2.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/Organization/organizationselector_angular.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/support/supportTicketDialog.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/online_angular.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/jquery.signalR-2.1.1.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/signalr.proxy.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/SignalR/iLang.SignalR.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/basemvc.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/Lume/alert.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/Lume/dropdown.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/Lume/modal.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/Lume/button.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/Lume/tags.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/Lume/tooltip.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/Lume/pagination.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/Lume/toast.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/Google/google.js?v=10.732.0"></script><script src="https://staticcdn.ulife.com.br/src.jq/MVCShared/disciplineModulestepHeader.js?v=10.732.0"></script>
    <script>
ILangSettings.UserID = 5606587;ILangSettings.UserName = 'Alexandre do Valle Nunes da Silva';ILangSettings.OrganizationID = 6483;ILangSettings.UserOrganizationID = 9166936;ILangSettings.Version = '10.732.0';ILangSettings.ClientIP = '186.204.57.175';ILangSettings.SynchronousEnabled = true;ILangSettings.SignalRLogEnabled = true;ILangSettings.Logout.AutenticationTimeout = 0;ILangSettings.Logout.LoginUrl = 'https://www.ulife.com.br/Login.aspx?Id=oRf6OzyxlaR2Y8Xb62g9fg%3d%3d';ILangSettings.Browser.OS = 'WinNT';ILangSettings.Browser.IsMobile = false;ILangSettings.IsUserAdmin= false;ILangSettings.IsUserStudent= true;ILangSettings.IsMasterILang= false;ILangSettings.CheckOrganizationChange= true;ILangSettings.MonitoringEnabled = true;ILangSettings.IsFlutterApp = false;ILangSettings.IsAndroidApp = false;ILangSettings.IsIosApp = false;ILangSettings.IsMobileApp = false;ILangSettings.init();
</script>

    <script src="https://staticcdn.ulife.com.br/src.jq/Plugin/PluginManager.js?v=10.732.0"></script>
    <script src="https://staticcdn.ulife.com.br/src.jq/resources/default.js?v=10.732.0"></script>
    
    <script src="https://staticcdn.ulife.com.br/src.jq/Lesson/Lessons.js?v=10.732.0"></script>

    <script type="module" src="https://cloudapp.animaeducacao.com.br/frontend-copilot-chat/widgets/copilot-chat/index.js"></script>
    <script type="module">
            import { register } from 'https://cloudapp.animaeducacao.com.br/frontend-copilot-chat/widgets/copilot-chat/index.js';
            register();
    </script>    

    
    <script type="module" src="https://cloudapp.animaeducacao.com.br/frontend-copilot-chat/widgets/banner-iara/index.js"></script>
    <script type="module">
        import { register } from 'https://cloudapp.animaeducacao.com.br/frontend-copilot-chat/widgets/banner-iara/index.js';
        register();
    </script>
    

    <script src="https://staticcdn.ulife.com.br/src.jq/StudentDigitalCredential/StudentDigitalIcon.js?v=10.732.0"></script>

    <script type="text/javascript">
        $('#topUserMenu').click(function (event) {
            event.stopPropagation();
        });

        $(window).click(function () {
            $('#topUserMenu').removeClass('active');
        });
    </script>

    <script type="module" src="https://comunicacaocdns3.ulife.com.br/widgets/notificacoes-drawer/index.js?v=10.732.0"></script>
<script type="module">
    import { register } from 'https://comunicacaocdns3.ulife.com.br/widgets/notificacoes-drawer/index.js?v=10.732.0';
    register();
</script>
<script src="https://staticcdn.ulife.com.br/src.jq/Microfrontend/Notificacao/MenuNotificacao.js?v=10.732.0"></script>
